### ISSUE TITLE
what kind of MPI it needs?

### ISSUE THREAD

**Issue by Alessandro-Barbieri** [bsc-pm/TCL#1] opened 2019-08-02 12:46 UTC
I can't configure. I'm using openmpi 3.1.3-11

```
checking mpi.h usability... yes
checking mpi.h presence... yes
checking for mpi.h... yes
checking whether the linker accepts -link_mpi=opt_mt... no
checking whether the linker accepts -mt_mpi... no
checking for library containing MPI_Init_thread... -lmpich
checking for library containing _ZN3MPI4Comm10DisconnectEv... -lmpichcxx
checking MPI library multithreading support... configure: error: in `/home/alessandro/sorgenti/TCL':
configure: error: 
------------------------------
The execution of MPI multithread support test failed
------------------------------
See `config.log' for more details
```
[config.log](https://github.com/bsc-pm/TCL/files/3461230/config.log)

**Comment by maarquitos14** [comment] 2019-08-05 08:58
Hi Alessandro,

Please, could you confirm that your MPI installation supports multithreaded executions? For doing so, you can compile and run the following code:

```
#include <mpi.h>
#include <assert.h>

int main (int argc, char **argv) {
    int provided;
    int err = MPI_Init_thread(&argc, &argv, MPI_THREAD_MULTIPLE, &provided);
    assert(err == MPI_SUCCESS && provided == MPI_THREAD_MULTIPLE);
}
```

**Comment by Alessandro-Barbieri** [comment] 2019-08-05 10:18
built and run
```
gcc provampi.c -lmpi -I/usr/lib/x86_64-linux-gnu/openmpi/include/
./a.out
```
no output

**Comment by maarquitos14** [comment] 2019-08-05 10:37
Alessandro, I suspect you are not using the OPENMPI installation for configuring the library. Note that in the configure output you posted in the first comment, the configure is detecting `lmpich` and `lmpichcxx`. That makes me think you may have another MPI installation, concretely a MPICH installation, without support for multithreaded executions. Could you provide us the configure line you used?

Thank you.

**Comment by Alessandro-Barbieri** [comment] 2019-08-05 10:41
`./configure --enable-instrumentation --with-mpi=/usr/lib/x86_64-linux-gnu/ --with-mpi-include=/usr/lib/x86_64-linux-gnu/openmpi/include/ --prefix=/usr/local --with-pic --enable-shared --disable-static`

**Comment by maarquitos14** [comment] 2019-08-05 10:44
If I am right, your openmpi installation is in `/usr/lib/x86_64-linux-gnu/openmpi/`. So, I suggest you to configure using the following command:
`./configure --enable-instrumentation --with-mpi=/usr/lib/x86_64-linux-gnu/openmpi/ --prefix=/usr/local --with-pic --enable-shared --disable-static`

**Comment by Alessandro-Barbieri** [comment] 2019-08-05 10:54
I purged the mpich packages (why I had both? Debian pulled them in) and now configure completes. Now it doesn't build.
```
make[1]: ingresso nella directory "/home/alessandro/sorgenti/TCL"
  CXX      src/debug_libtcl_la-Bootstrap.lo
In file included from /usr/lib/x86_64-linux-gnu/openmpi/include/openmpi/ompi/mpi/cxx/mpicxx.h:277,
                 from /usr/lib/x86_64-linux-gnu/openmpi/include/mpi.h:2684,
                 from ./api/tcl/bootstrap.h:12,
                 from ./api/tcl.h:10,
                 from src/Bootstrap.cpp:7:
/usr/lib/x86_64-linux-gnu/openmpi/include/openmpi/ompi/mpi/cxx/op_inln.h: In member function ‘virtual void MPI::Op::Init(void (*)(const void*, void*, int, const MPI::Datatype&), bool)’:
/usr/lib/x86_64-linux-gnu/openmpi/include/openmpi/ompi/mpi/cxx/op_inln.h:121:46: error: cast between incompatible function types from ‘void (*)(void*, void*, int*, ompi_datatype_t**, void (*)(void*, void*, int*, ompi_datatype_t**))’ to ‘void (*)(void*, void*, int*, ompi_datatype_t**)’ [-Werror=cast-function-type]
     (void)MPI_Op_create((MPI_User_function*) ompi_mpi_cxx_op_intercept,
                                              ^~~~~~~~~~~~~~~~~~~~~~~~~
/usr/lib/x86_64-linux-gnu/openmpi/include/openmpi/ompi/mpi/cxx/op_inln.h:123:59: error: cast between incompatible function types from ‘void (*)(const void*, void*, int, const MPI::Datatype&)’ to ‘void (*)(void*, void*, int*, ompi_datatype_t**)’ [-Werror=cast-function-type]
     ompi_op_set_cxx_callback(mpi_op, (MPI_User_function*) func);
                                                           ^~~~
cc1plus: all warnings being treated as errors
make[1]: *** [Makefile:995: src/debug_libtcl_la-Bootstrap.lo] Error 1
make[1]: uscita dalla directory "/home/alessandro/sorgenti/TCL"
make: *** [Makefile:747: all] Error 2
```

**Comment by maarquitos14** [comment] 2019-08-05 12:49
Alessandro, we are not able to reproduce your error. It seems that two headers are providing different prototypes for a given function.  Please, could you send us the `config.log`? Also, could you add `V=1` to your `make` command and send us the output?

**Comment by Alessandro-Barbieri** [comment] 2019-08-05 19:33
```
make V=1
mkdir -p tcl ; \
./scripts/generate_multidimensional_register_prototypes.sh 8 > tcl/multidimensional-register.h
./scripts/generate_multidim_functions.sh 8 > MultidimensionalRegister.cpp
make  all-am
make[1]: ingresso nella directory "/home/alessandro/sorgenti/TCL"
/bin/bash ./libtool  --tag=CXX   --mode=compile g++ -DHAVE_CONFIG_H -I.  -I. -I./src/  -I/usr/lib/x86_64-linux-gnu/openmpi/include -I/usr/local/include -I/usr/local/include -I/usr/local/include -I. -I./src/  -I./api/  -DLIBDIR='/usr/local/lib' -DFTI_BACKEND -DSCR_BACKEND -DVELOC_BACKEND -Wdate-time -D_FORTIFY_SOURCE=2 -I. -I./src/  -Wall -Wextra -Wshadow -Wmissing-declarations -Wno-unused-parameter -Wno-missing-field-initializers -Werror -O0 -g2 -fno-inline -DFTI_BACKEND -DSCR_BACKEND -DVELOC_BACKEND -fPIC -DREENTRANT -fstack-protector-strong -Wformat -Wdate-time -D_FORTIFY_SOURCE=2 -MT src/debug_libtcl_la-Bootstrap.lo -MD -MP -MF src/.deps/debug_libtcl_la-Bootstrap.Tpo -c -o src/debug_libtcl_la-Bootstrap.lo `test -f 'src/Bootstrap.cpp' || echo './'`src/Bootstrap.cpp
libtool: compile:  g++ -DHAVE_CONFIG_H -I. -I. -I./src/ -I/usr/lib/x86_64-linux-gnu/openmpi/include -I/usr/local/include -I/usr/local/include -I/usr/local/include -I. -I./src/ -I./api/ -DLIBDIR=/usr/local/lib -DFTI_BACKEND -DSCR_BACKEND -DVELOC_BACKEND -Wdate-time -D_FORTIFY_SOURCE=2 -I. -I./src/ -Wall -Wextra -Wshadow -Wmissing-declarations -Wno-unused-parameter -Wno-missing-field-initializers -Werror -O0 -g2 -fno-inline -DFTI_BACKEND -DSCR_BACKEND -DVELOC_BACKEND -fPIC -DREENTRANT -fstack-protector-strong -Wformat -Wdate-time -D_FORTIFY_SOURCE=2 -MT src/debug_libtcl_la-Bootstrap.lo -MD -MP -MF src/.deps/debug_libtcl_la-Bootstrap.Tpo -c src/Bootstrap.cpp  -fPIC -DPIC -o src/.libs/debug_libtcl_la-Bootstrap.o
In file included from /usr/lib/x86_64-linux-gnu/openmpi/include/openmpi/ompi/mpi/cxx/mpicxx.h:277,
                 from /usr/lib/x86_64-linux-gnu/openmpi/include/mpi.h:2684,
                 from ./api/tcl/bootstrap.h:12,
                 from ./api/tcl.h:10,
                 from src/Bootstrap.cpp:7:
/usr/lib/x86_64-linux-gnu/openmpi/include/openmpi/ompi/mpi/cxx/op_inln.h: In member function ‘virtual void MPI::Op::Init(void (*)(const void*, void*, int, const MPI::Datatype&), bool)’:
/usr/lib/x86_64-linux-gnu/openmpi/include/openmpi/ompi/mpi/cxx/op_inln.h:121:46: error: cast between incompatible function types from ‘void (*)(void*, void*, int*, ompi_datatype_t**, void (*)(void*, void*, int*, ompi_datatype_t**))’ to ‘void (*)(void*, void*, int*, ompi_datatype_t**)’ [-Werror=cast-function-type]
     (void)MPI_Op_create((MPI_User_function*) ompi_mpi_cxx_op_intercept,
                                              ^~~~~~~~~~~~~~~~~~~~~~~~~
/usr/lib/x86_64-linux-gnu/openmpi/include/openmpi/ompi/mpi/cxx/op_inln.h:123:59: error: cast between incompatible function types from ‘void (*)(const void*, void*, int, const MPI::Datatype&)’ to ‘void (*)(void*, void*, int*, ompi_datatype_t**)’ [-Werror=cast-function-type]
     ompi_op_set_cxx_callback(mpi_op, (MPI_User_function*) func);
                                                           ^~~~
cc1plus: all warnings being treated as errors
make[1]: *** [Makefile:995: src/debug_libtcl_la-Bootstrap.lo] Error 1
make[1]: uscita dalla directory "/home/alessandro/sorgenti/TCL"
make: *** [Makefile:747: all] Error 2
```
[config.log](https://github.com/bsc-pm/TCL/files/3469033/config.log)

**Comment by maarquitos14** [comment] 2019-08-06 13:59
I am afraid you still have several MPI headers in your system. Could you check so? The good one should be inside `/usr/lib/x86_64-linux-gnu/openmpi/include`. Maybe you have other MPI headers in 
`/usr/local/include`. Could you check?

**Comment by Alessandro-Barbieri** [comment] 2019-08-06 16:57
I searched all the headers after an `updatedb`
```
locate mpi.h
/home/alessandro/sorgenti/GASNet-2019.6.0/other/ammpi/ammpi.h
/home/alessandro/sorgenti/KVTree/src/kvtree_mpi.h
/home/alessandro/sorgenti/LaunchMON/launchmon/src/linux/lmon_api/lmon_be_sync_mpi.hxx
/home/alessandro/sorgenti/extrae/src/common/MPI/utils_mpi.h
/home/alessandro/sorgenti/extrae/src/tracer/trace_macros_mpi.h
/home/alessandro/sorgenti/mbdyn-1.7.3/include/ac/mpi.h
/home/alessandro/sorgenti/mcxx/src/tl/omp/nanox-nodecl/devices/mpi/nanox-mpi.hpp
/home/alessandro/sorgenti/nanox-0.15/src/arch/mpi/nanos-mpi.h
/home/alessandro/sorgenti/rankstr/src/rankstr_mpi.h
/home/alessandro/sorgenti/scr/src/scr_flush_file_mpi.h
/home/alessandro/sorgenti/scr/src/scr_hash_mpi.h
/home/alessandro/sorgenti/scr/src/scr_path_mpi.h
/home/alessandro/sorgenti/scr/src/scr_util_mpi.h
/home/alessandro/sorgenti/sionlib/build-linux-gomp-openmpi/build/cppinterface/sion_cxx_mpi.hpp
/home/alessandro/sorgenti/sionlib/build-linux-gomp-openmpi/build/cppinterface/sion_cxx_ompi.hpp
/home/alessandro/sorgenti/sionlib/build-linux-gomp-openmpi/build/examples/par_mandel/mandelmpi.h
/home/alessandro/sorgenti/sionlib/build-linux-gomp-openmpi/build/fortraninterface/sion_fortran_mpi.h
/home/alessandro/sorgenti/sionlib/build-linux-gomp-openmpi/build/fortraninterface/sion_fortran_ompi.h
/home/alessandro/sorgenti/sionlib/build-linux-gomp-openmpi/build/parlib/sion_datatypes_mpi.h
/home/alessandro/sorgenti/sionlib/build-linux-gomp-openmpi/build/parlib/sion_mpi.h
/home/alessandro/sorgenti/sionlib/build-linux-gomp-openmpi/build/parlib/sion_ompi.h
/home/alessandro/sorgenti/sionlib/examples/par_mandel/mandelmpi.h
/home/alessandro/sorgenti/sionlib/src/cppinterface/sion_cxx_mpi.hpp
/home/alessandro/sorgenti/sionlib/src/cppinterface/sion_cxx_ompi.hpp
/home/alessandro/sorgenti/sionlib/src/fortraninterface/sion_fortran_mpi.h
/home/alessandro/sorgenti/sionlib/src/fortraninterface/sion_fortran_ompi.h
/home/alessandro/sorgenti/sionlib/src/parlib/sion_datatypes_mpi.h
/home/alessandro/sorgenti/sionlib/src/parlib/sion_mpi.h
/home/alessandro/sorgenti/sionlib/src/parlib/sion_ompi.h
/home/alessandro/sorgenti/sionlibl/build-linux-gomp-openmpi/build/cppinterface/sion_cxx_mpi.hpp
/home/alessandro/sorgenti/sionlibl/build-linux-gomp-openmpi/build/cppinterface/sion_cxx_ompi.hpp
/home/alessandro/sorgenti/sionlibl/build-linux-gomp-openmpi/build/examples/par_mandel/mandelmpi.h
/home/alessandro/sorgenti/sionlibl/build-linux-gomp-openmpi/build/fortraninterface/sion_fortran_mpi.h
/home/alessandro/sorgenti/sionlibl/build-linux-gomp-openmpi/build/fortraninterface/sion_fortran_ompi.h
/home/alessandro/sorgenti/sionlibl/build-linux-gomp-openmpi/build/parlib/sion_datatypes_mpi.h
/home/alessandro/sorgenti/sionlibl/build-linux-gomp-openmpi/build/parlib/sion_mpi.h
/home/alessandro/sorgenti/sionlibl/build-linux-gomp-openmpi/build/parlib/sion_ompi.h
/home/alessandro/sorgenti/sionlibl/examples/par_mandel/mandelmpi.h
/home/alessandro/sorgenti/sionlibl/src/cppinterface/sion_cxx_mpi.hpp
/home/alessandro/sorgenti/sionlibl/src/cppinterface/sion_cxx_ompi.hpp
/home/alessandro/sorgenti/sionlibl/src/fortraninterface/sion_fortran_mpi.h
/home/alessandro/sorgenti/sionlibl/src/fortraninterface/sion_fortran_ompi.h
/home/alessandro/sorgenti/sionlibl/src/parlib/sion_datatypes_mpi.h
/home/alessandro/sorgenti/sionlibl/src/parlib/sion_mpi.h
/home/alessandro/sorgenti/sionlibl/src/parlib/sion_ompi.h
/usr/include/boost/mpi.hpp
/usr/include/boost/graph/use_mpi.hpp
/usr/include/boost/numeric/odeint/external/mpi/mpi.hpp
/usr/include/hdf/hcompi.h
/usr/include/hdf5/openmpi/H5FDmpi.h
/usr/include/hdf5/serial/H5FDmpi.h
/usr/include/mumps_seq/mpi.h
/usr/include/vtk-7.1/vtkdiy/mpi.hpp
/usr/lib/x86_64-linux-gnu/openmpi/include/mpi.h
/usr/lib/x86_64-linux-gnu/openmpi/include/openmpi/ompi/mpi/fortran/mpif-h/prototypes_mpi.h
/usr/local/examples/par_mandel/mandelmpi.h
/usr/local/include/kvtree_mpi.h
/usr/local/include/rankstr_mpi.h
/usr/local/include/sion_cxx_mpi.hpp
/usr/local/include/sion_cxx_ompi.hpp
/usr/local/include/sion_datatypes_mpi.h
/usr/local/include/sion_mpi.h
/usr/local/include/sion_ompi.h
/usr/local/include/mpi-conduit/ammpi.h
/usr/local/include/nanox/nanos-mpi.h
/usr/local/share/doc/otf2/html/group__usage__reading__mpi.html
/usr/local/share/doc/otf2/html/group__usage__writing__mpi.html
/usr/local/src/arch/mpi/nanos-mpi.h
/usr/share/doc/octave/octave.html/XREFstrcmpi.html
/usr/share/doc/octave/octave.html/XREFstrncmpi.html
/usr/src/linux-headers-4.19.0-5-common/include/linux/mpi.h
```

**Comment by maarquitos14** [comment] 2019-08-07 07:12
Alessandro, I was looking at this issue in the OpenMPI github: 

[(https://github.com/open-mpi/ompi/issues/5157)]

They are facing the same problem than you. I have seen there is a workaround that is defining `OMPI_SKIP_MPICXX`. I'll try to push a fix as soon as possible. Meanwhile, I think it should work configuring with this command:
`./configure --enable-instrumentation --with-mpi=/usr/lib/x86_64-linux-gnu/openmpi/ --prefix=/usr/local --with-pic --enable-shared --disable-static CPPFLAGS="-DOMPI_SKIP_MPICXX"`

**Comment by maarquitos14** [comment] 2019-08-08 10:37
I have just pushed a fix. Please, let us know if this works for you.

**Comment by Alessandro-Barbieri** [comment] 2019-08-08 15:39
It doesn't work

**Comment by maarquitos14** [comment] 2019-08-09 10:34
Did you make `autoreconf -fiv`?

**Comment by Alessandro-Barbieri** [comment] 2019-08-09 17:23
Yes after a fresh clone

**Comment by maarquitos14** [comment] 2019-08-10 18:16
And is it the same error than before?

**Comment by Alessandro-Barbieri** [comment] 2019-08-12 16:01
yes

**Comment by maarquitos14** [comment] 2019-08-22 10:20
It should be fixed now.

**Closed as completed** 2019-08-22 22:42 UTC
